apiVersion: apps/v1
kind: Deployment
metadata:
  name: bahttleship-deployment
  labels:
    app: bahttleship
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bahttleship
  template:
    metadata:
      labels:
        app: bahttleship
    spec:
      containers:
      - name: bahttleship
        image: docker.io/0xniel/bahttleship:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
